version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres

  # PostgreSQL service for local development
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=queryassistant
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
